# This is a basic workflow to help you get started with Actions

name: Integración y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      Nombre: "Hector"
      Apellido: "Cconislla Ventura"
      Edad: 28

      Titulo: "Presentacion"
      Minombre: "Hector Cconislla Ventura 28"

      user: ${{ secrets.User }}
      password: ${{ secrets.Password }}
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Imprime variables de entorno
      - name: Imprime variables de entorno
        run: |
          echo "La variable Nombre es: ${{ env.Nombre }}"
          echo "La variable Apellido es: ${{ env.Apellido }}"
          echo "La variable Edad es: ${{ env.Edad }}"
      
      # Mi primer Step
      - name: Mi primer impresion de STEP
        run: |
          echo "Mi primer impresion de Titulo es: ${{ env.Titulo }}"
          echo "Mi primer impresion de Minombre es: ${{ env.Minombre }}"
          
      # Mi Segundo Step
      - name: Datos Generales
        run: |
          echo Carrera: Ingenieria de Sistemas.   
      
      # Impresion de variables Secretas
      - name: Impresion de variables Secretas
        run: |
          echo "El usuario es: ${{ secrets.User }}"
          echo "La contraseña es: ${{ secrets.Password }}"